---
title: "Date and Time"
author: "Uday Allu"
date: "28 January 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Basic Day Difference

```{r}
x=as.Date("2012-03-01")
y=as.Date("2012-01-28")
x-y
```
Knowing the time difference 
```{r}
x=as.POSIXct("2012-10-25 01:00:00")
y=as.POSIXct("2012-10-25 06:00:00", tz="GMT")
y-x
```
Combine the date and time 
```{r}
dates <- c("02/27/92", "02/27/92", "01/14/92", "02/28/92", "02/01/92")
times <- c("23:03:20", "22:29:56", "01:03:30", "18:21:03", "16:56:26")
x <- paste(dates, times)
strptime(x, "%m/%d/%y %H:%M:%S")
```

```{r}
## time with fractional seconds
z <- strptime("20/2/06 11:16:16.683", "%d/%m/%y %H:%M:%OS")
z # prints without fractional seconds
op <- options(digits.secs = 3)
z
```
```{r}
 theDates <- c("1 jan 2012","1 jan 2013","1 jan 2014")
 dateFields <- as.Date(theDates,"%d %b %Y")
 ds1=c()
dateFields
year=as.POSIXlt(dateFields)$Year+1900)
year
```



